name: flutter_starter_template
description: Flutter Starter Project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #Add Packages Here

  cupertino_icons: ^1.0.2 #icon package

  get: ^4.6.5 # getx package for state and route management

  dio: ^4.0.6 # for all http connection

  pretty_dio_logger: ^1.1.1 # logging http requests on console

  shared_preferences: ^2.0.12 # to store keys on storage

  freezed_annotation: ^2.2.0 # model generation

  json_annotation: ^4.7.0 # model to json & vice versa

  fluttertoast:
    path: packages/fluttertoast-8.0.8/

  intl: ^0.17.0 # for date and time formatting

dev_dependencies:
  flutter_test:
    sdk: flutter

  #Add Development Packages Here
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  freezed: ^2.2.1
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # list giving the asset and other descriptors for the font. For example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
